FROM python:3.11-slim AS build
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir grpcio-tools==1.65.1 protobuf==5.26.1
COPY sentiment.proto .
RUN python -m grpc_tools.protoc -I. \
  --python_out=. --grpc_python_out=. sentiment.proto

FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    grpcio==1.65.1 \
    protobuf==5.26.1 \
    googleapis-common-protos==1.63.2 \
    pymongo==4.8.0 \
    redis==5.0.7
COPY --from=build /app/sentiment_pb2.py /app/sentiment_pb2.py
COPY --from=build /app/sentiment_pb2_grpc.py /app/sentiment_pb2_grpc.py
COPY consumer.py .
CMD ["python", "consumer.py"]
