FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    grpcio==1.65.1 \
    grpcio-tools==1.65.1 \
    protobuf==5.26.1 \
    googleapis-common-protos==1.63.2

COPY sentiment.proto .
RUN python -m grpc_tools.protoc -I. \
    --python_out=. \
    --grpc_python_out=. \
    sentiment.proto

COPY server.py .
ENV PORT=50051
EXPOSE 50051
CMD ["python", "server.py"]