FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN pip install --no-cache-dir fastapi==0.112.2 uvicorn==0.30.6 motor==3.6.0 pydantic==2.8.2 python-dateutil==2.9.0.post0
COPY main.py .
ENV PORT=8000
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
